#!/usr/bin/env bash

while true; do
    echo "Starting main in 5"
    pip3 install -r /home/pi/d_sh_handler/requirements.txt
    echo "Starting main"
    sleep 5
    python3 /home/pi/d_sh_handler/main.py
done