name: Service workflow

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
      # - '*'         # matches every branch that doesn't contain a '/'
      # - '*/*'       # matches every branch containing a single '/'
      # - '**'        # matches every branch
      
env:
  LOCAL: True

jobs:
  
  local-deploy:
    runs-on: self-hosted
    steps:
      - name: Clone repo or pull changes
        shell: bash
        run: |
          REPO_DIR="/home/denis/$(basename ${{ github.repository }})"

          # Check if the repository directory exists
          if [ ! -d "$REPO_DIR" ]; then
            echo "Repository not found. Cloning..."
            cd /home/denis
            git clone https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
            cd $(basename ${{ github.repository }})
          else
            echo "Repository found. Pulling latest changes..."
            cd $REPO_DIR
            git reset --hard
            git pull --rebase
          fi
      - name: Checkout
        shell: bash
        run: |
          # Checkout the desired branch
          git checkout ${{ github.ref_name }}
      - name: set env variables
        shell: bash
        run: |
          echo "BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }}" > /home/denis/d_sh_handler/.env
          echo "TG_ADMIN_ID=${{ secrets.TG_ADMIN_ID }}" >> /home/denis/d_sh_handler/.env
          echo "GPT_API_KEY=${{ secrets.GPT_API_KEY }}" >> /home/denis/d_sh_handler/.env
      - name: Log new version to trigger service
        shell: bash
        run: |
          chmod 777 /home/denis/d_sh_handler/run.sh
          echo "1" > /home/denis/version.log
